### ISSUE TITLE
AdGuard DNS false positives

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#8] opened 2018-10-15 11:07 UTC
Originally reported here 1978293, I managed to reproduce it in Adguard Pro with both Default and Family DNS.

1) **crystalout.surfernetwork.com** 

This is a legitimate domain from which multiple online radio stations stream themselves. Examples (all work in Windows Media Player, Winamp, VLC, mplayer, etc.):

http://crystalout.surfernetwork.com:8001/KCXL_MP3
http://crystalout.surfernetwork.com:8001/KSJB_MP3

(These radio stations' home pages are www.kcxl.com and ksjbam.com.)

2) **my.mixtape.moe**
3) **files.catbox.moe** 

Both of these domains belong to the file upload/download services https://mixtape.moe/ and https://catbox.moe/. These are also legit services, which sometimes experience abuse by users. When the abuse is reported, the hosts remove the offending files. Their entire domains should not be blocked, as 99% of the legitimate users cannot upload or download from them as a result.

**Comment by Alex-302** [comment] 2018-10-15 11:49
1, 3 - blocked by safe browsing. Will be fixed.
2 - removed bad rule

**Closed by Alex-302** 2018-10-15 11:49 UTC

**Comment by veronikasav** [comment] 2018-11-07 18:55
@Alex-302, the issue with my.mixtape.moe is back. Could you please check it again?

**Comment by Alex-302** [comment] 2018-11-07 21:38
@veronikasav I can't reproduce. Please read our chat - `19:53`

**Comment by Yevhen1996** [comment] 2018-12-14 18:03
@Alex-302 the user is back with the issue. Looks like my.mixtape.moe is getting blocked by Standard DNS, could you please check this again?

**Comment by Alex-302** [comment] 2018-12-14 18:20
@Yevhen1996 
![image](https://user-images.githubusercontent.com/8361299/50020118-a8d22600-ffdd-11e8-9bc6-1bd0176a0e07.png)
