### ISSUE TITLE
AdGuardDNS breaks Mail Privacy Protection in iOS 15

### ISSUE THREAD

**Issue by TimofeyK** [AdguardTeam/AdGuardSDNSFilter#764] opened 2021-09-21 10:30 UTC
### Steps to reproduce

1. Use iOS 15
2. Enable Protect Mail Activity in Settings - Mail -  Privacy Protection 
3. Configure AdGuard DNS 
4. Receive new emails in Mail app - Pictures are not loading
Warning shown: Unable to load remote content privately
5. Disable AdGuard DNS and open same emails - pictures are loading normally 

### Expected behavior

External content, e.g. pictures, should load normally when using AdGuard DNS

### Actual behavior

Pictures are not loading
Warning shown: Unable to load remote content privately

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default, 94.140.14.14
| How did you setup DNS configuration:| System profile
| Device model:| iPhone 12 Pro
| Operating system and version:| iOS 15.0

**Comment by ameshkov** [comment] 2021-09-21 10:53
Hm, I cannot reproduce this. What mail provider do you use?

**Comment by TimofeyK** [comment] 2021-09-21 11:05
Gmail. For me reproduces consistently. Tried multiple times with the same result - images are not loading with Mail Privacy on and AdGuardDNS. If I turn one these off - everything loads immediately

**Comment by TimofeyK** [comment] 2021-09-21 11:09
Just checked - same happens with iCloud mailbox too

Tried restarting the phone - still reproduces

**Comment by ameshkov** [comment] 2021-09-21 12:09
What's weird about that is that I can reproduce the issue with other DNS providers as well, it's not specific to AG DNS.

**Comment by ameshkov** [comment] 2021-09-21 12:17
Yeah, it works okay when I am using the system DNS, but once I start using any other DNS (Google, Cloudflare, AG), it stops working.

**Comment by ameshkov** [comment] 2021-09-21 12:18
Moreover, if I enable VPN, it starts working again. This all is quite weird.

**Comment by 24khxn** [comment] 2021-09-25 18:06
Any updates on a workaround for now? Is there anything we could whitelist?

**Comment by ameshkov** [comment] 2021-09-27 09:04
Nope, as far as I understand this is not a blocklist issue. Not even a particular DNS server issue since it happens with almost every DNS resolver for me.

**Comment by jeanlst** [comment] 2021-11-22 16:12
@24khxn the workaround I found was to switch from Split-Tunnel to Full-Tunnel in the Low-Level Advance Settings

**Comment by jeanlst** [comment] 2021-11-22 16:13
Any news on this issue? When is it going to work again with the Split-Tunnel?

**Comment by ameshkov** [comment] 2021-11-22 16:26
Nothing new here. Reported it to Apple but they easily can consider this intended behavior.

Closing this issue since there's nothing to change in the DNS filter. The discussion can be continued, of course.

**Closed by ameshkov** 2021-11-22 16:26 UTC
