### ISSUE TITLE
click.simba.taobao.com incorrect blocking

### ISSUE THREAD

**Issue by liyinsg** [AdguardTeam/AdGuardSDNSFilter#345] opened 2020-05-29 05:25 UTC
Content pages in taobao.com were blocked.

### Steps to reproduce

1. Search anything in taobao.com
2. Goods from search result are blocked by adguard

### Actual behavior

<details><summary>Screenshot:</summary>

![Untitled](https://user-images.githubusercontent.com/4927363/83251664-81c0e180-a1dc-11ea-8bc9-45ef251118c3.jpg)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (e.g. Default, 176.103.130.130)
| How did you setup DNS configuration:| (System/DNSCrypt app/Router)
| Device model:| (e.g. Google Pixel)
| Operating system and version:| (e.g. Android 7.1.2)

**Comment by slavaleleka** [comment] 2020-05-29 08:06
@liyinsg I see no incorrectly blocked content. could you please specify:
- the link where it happens;
- some screenshots how it actually looks like;
- any steps to reproduce the problem?

**Comment by liyinsg** [comment] 2020-05-29 10:49
@slavaleleka screenshot uploaded, as you can see the link to the goods are blocked

**Comment by Alex-302** [comment] 2020-05-29 18:35
Fixed in https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/346

**Closed** 2020-05-29 18:35 UTC
